#ifndef UNIT_TEST_H
#define UNIT_TEST_H

const char *test_files[] = {"../test/integration/agecontrol/agecontrol.mc",
                            "../test/integration/binary_search/binary_search.mc",
                            "../test/integration/dangling_else/dangling_else.mc",
                            "../test/integration/dijkstra/dijkstra.mc",
                            "../test/integration/draw/draw.mc",
                            "../test/integration/empty/empty.mc",
                            "../test/integration/euclid/euclid.mc",
                            "../test/integration/euclidean_division/euclidean_division.mc",
                            "../test/integration/factorial/factorial.mc",
                            "../test/integration/fem/fem.mc",
                            "../test/integration/fib/fib.mc",
                            "../test/integration/flw/flw.mc",
                            "../test/integration/gcd/gcd.mc",
                            "../test/integration/intToBin/intToBin.mc",
                            "../test/integration/is_square/is_square.mc",
                            "../test/integration/leap_year/leap_year.mc",
                            "../test/integration/leibniz_pi/leibniz_pi.mc",
                            "../test/integration/lucas_number/lucas_number.mc",
                            "../test/integration/mandelbrot/mandelbrot.mc",
                            "../test/integration/nim/nim.mc",
                            "../test/integration/nonsense/nonsense.mc",
                            "../test/integration/number_guessing/number_guessing.mc",
                            "../test/integration/operator_precedence/operator_precedence.mc",
                            "../test/integration/palindrome/palindrome.mc",
                            "../test/integration/pass_array/pass_array.mc",
                            "../test/integration/prime/prime.mc",
                            "../test/integration/shadowing/shadowing.mc",
                            "../test/integration/slowsort/slowsort.mc",
                            "../test/integration/sorting_network/sorting_network.mc",
                            "../test/integration/subset_sum/subset_sum.mc",
                            "../test/integration/supersyntaxchecker2000/supersyntaxchecker2000.mc",
                            "../test/integration/taylor/taylor.mc"};

#endif
